### ISSUE TITLE
Underflow detected... on rpi

### ISSUE THREAD

**Issue by lorenzoromagnoli** [mmende/soundengine#1]
I'm trying running this to record realtime audio and perform a fft on a raspberry pi. 
constantly getting 'Underflow detected...' error. any suggestion on how to solve it?

**Comment by mmende** [comment]
Hi,

I only added the underflow detected message for debugging purposes of an own project. The module basically uses an own portaudio thread to fetch and push audio packages from and to the soundcard and a async function that works on these data and exposes them to the nodejs app. If the async function is not fast enough the portaudio thread has no audio packages to push to the soundcard what is meant with underflow detected. The first underflow message is unavoidable and can be ignored. If the node thread has some heavy lifting to do or needs some startup time it will not be able to process the queued audio packages fast enough... to bring the two threads in sync you can try to call the `synchronize()` method a short while after the app has started. This method will clear the audio buffer queue and the delay between the threads should be minimized. However since rpi's have not the fastest hardware I can imagine that there always will be a delay between the audio input and output.

**Comment by lorenzoromagnoli** [comment]
Indeed, I think I was trying to process too much stuff on the node thread. I changed the way I was computing the fft and I'm not getting the error anymore. 

thanks
