### ISSUE TITLE
Possibility to Capture Speaker Input

### ISSUE THREAD

**Issue by ghost** [mmende/soundengine#2]
I've been scouring the web to find a NodeJs library that could interact with the soundcard to record audio that is coming from an output device such as speakers so that I could send it over to another application and play it there. Does this framework have that capability? If so how could this be accomplished? If not, does anyone know one that can?

**Comment by mmende** [comment]
Hi,
Since this module uses portaudio underneath to interact with audio devices it depends on the capabilities of this library. Portaudio figures out how many input and output channels each audio device supports and than allows this module to use them as record or output device based on that. Therefore I doubt it would be possible to use a speaker as input device. I guess to accomplish something like that you'd have to at least start your implementation at the OS's sound APIs level if even possible.

Kind regards
